// Generated by LiveScript 1.2.0
var main;
main = function($scope, $timeout){
  var canvas, ctx, img, rhptr, resizeCanvas, resizeHandler;
  canvas = document.getElementById("canvas");
  ctx = canvas.getContext("2d");
  img = new Image();
  img.src = "lien.png";
  rhptr = null;
  resizeCanvas = function(){
    var ref$, w, h, cw, ch, bw, bh, fs, r, count, text, otext, texts, i, tw, y, i$, len$, t;
    ref$ = [$('#canvas-html').width(), $('#canvas-html').height()], w = ref$[0], h = ref$[1];
    ref$ = [w, h], cw = ref$[0], ch = ref$[1];
    w <= h || (w = h);
    h <= w || (h = w);
    ref$ = [w * 0.63, h * 0.39].map(function(it){
      return parseInt(it);
    }), bw = ref$[0], bh = ref$[1];
    ctx.drawImage(img, parseInt((cw - w) / 2), 0, w, h);
    fs = bw;
    r = fs / 2;
    while (r > 0.5) {
      count = (bw / fs) * (bh / fs);
      if (count < $scope.text.length) {
        fs -= r;
      } else {
        fs += r;
      }
      r = r * 0.5;
    }
    console.log("字型大小:", fs);
    fs <= (ref$ = bw / 5) || (fs = ref$);
    ctx.font = fs + "px Arial";
    text = otext = $scope.text;
    texts = [];
    i = 1;
    while (otext.length) {
      text = otext.substring(0, i);
      tw = ctx.measureText(text).width;
      if (i >= otext.length || tw >= bw * 0.9) {
        texts.push(text);
        if (i >= otext.length) {
          break;
        }
        otext = otext.substring(i);
        i = 0;
      }
      i++;
    }
    y = (bh - texts.length * fs) / 2;
    i = 0;
    ctx.rotate(-4 * Math.PI / 180);
    for (i$ = 0, len$ = texts.length; i$ < len$; ++i$) {
      t = texts[i$];
      ctx.fillText(t, cw / 2 - bw * 0.6, ch * 0.65 + y + i * fs);
      i++;
    }
    ctx.rotate(4 * Math.PI / 180);
    return $('#textbox').css({
      width: bw + "px",
      height: bh + "px",
      left: (cw / 2 - bw * 0.6) + "px",
      top: ch / 2 + "px",
      opacity: 1,
      fontSize: fs + "px"
    });
  };
  resizeHandler = function(){
    var ref$, w, h, cw, ch, bw, bh;
    rhptr = null;
    ref$ = [$('#canvas-html').width(), $('#canvas-html').height()], w = ref$[0], h = ref$[1];
    ref$ = [w, h], cw = ref$[0], ch = ref$[1];
    w <= h || (w = h);
    h <= w || (h = w);
    ref$ = [w * 0.63, h * 0.39].map(function(it){
      return parseInt(it);
    }), bw = ref$[0], bh = ref$[1];
    $('#canvas').attr({
      width: cw + "px",
      height: ch + "px"
    });
    $('#canvas').css({
      width: cw + "px",
      height: ch + "px"
    });
    return $timeout(resizeCanvas, 100);
  };
  $(window).resize(function(){
    if (rhptr) {
      $timeout.cancel(rhptr);
    }
    return rhptr = $timeout(resizeHandler, 100);
  });
  $scope.text = "我是連勝文大家好我是連勝文大家好我是連勝文大家好";
  $timeout(resizeHandler, 100);
  return $scope.$watch('text', function(){
    return resizeHandler();
  });
};